# Generated by Django 5.0.1 on 2024-03-08 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='discription',
            new_name='description',
        ),
    ]
