# Generated by Django 5.0.1 on 2024-03-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_film_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='date',
            field=models.TextField(default='Date'),
        ),
    ]
