# Generated by Django 5.0.1 on 2024-03-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_film_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='contry',
            field=models.CharField(default='Country', max_length=100),
        ),
    ]
