# Generated by Django 5.0.1 on 2024-03-09 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Comment',
        ),
    ]
